### ISSUE TITLE
Error on DemoProject

### ISSUE THREAD

**Issue by benMohamed** [metasmile/NSGIF2#14]
Hi, 
When i try to build the demoProject with Xcode 8.2.1 i get the attachd error, 
<img width="884" alt="screen shot 2017-03-08 at 12 26 01" src="https://cloud.githubusercontent.com/assets/8136464/23703944/6f1290b6-03fa-11e7-8f0a-1f910c4a2b02.png">

**Comment by metasmile** [comment]
1.5.3 was released. https://github.com/metasmile/NSGIF2/releases/tag/1.5.3
Thanks for your report.
